### ISSUE TITLE
Datamapper XML transformation broken

### ISSUE THREAD

**Issue by isudana** [wso2/product-ei#3711] opened 2019-04-12 13:35 UTC
Not properly working when there are namespaces in the XML payload which is a basic scenario

**Comment by Drifftr** [comment] 2019-04-18 11:50
Duplicate of https://github.com/wso2/product-ei/issues/3705

**Comment by isudana** [comment] 2019-05-09 14:37
This is not working even in the latest pack. 
Realtime preview works fine, but generated xslt does not contain namespace declarations.

**Comment by Drifftr** [comment] 2019-05-09 19:01
Added custom namespaces to XSLT style sheets https://github.com/wso2/devstudio-tooling-esb/pull/927

**Comment by prabushi** [comment] 2019-05-09 19:31
Fixed in https://github.com/wso2/devstudio-tooling-esb/pull/927

**Closed by prabushi** 2019-05-09 19:31 UTC
Labels: EI Tooling, Severity/Blocker
