### ISSUE TITLE
UI issue in representing 'DS Scheduled Tasks' in Navigation menu

### ISSUE THREAD

**Issue by sashikamw** [wso2/product-ei#878] opened 2017-08-16 04:33 UTC
Environment
EI - EI 6.2.0 M2 pack
Browser - Version 58.0.3029.96 (64-bit)

**Issue**
There is a UI issue in presenting "DS Scheduled Tasks" in the left navigator. (Note - Screen size is 100% )

![scheduledtask](https://user-images.githubusercontent.com/14962228/29347353-ba1419ac-8269-11e7-8055-f42be4df0c58.png)

**Comment by himasha** [comment] 2017-08-30 02:07
Unable to reproduce in EI -6.2.0-m3 pack. Checked in both chrome (version 59.0.3071.115) and Firefox with screen size 100%.

**Closed by himasha** 2017-08-30 02:07 UTC
Labels: 6.2.0, Component/Integrator, UI
