### ISSUE TITLE
Inline throttle policy editor does not load the content properly

### ISSUE THREAD

**Issue by Shakila** [wso2/product-ei#2091] opened 2018-04-04 05:39 UTC
**Description:**
When we edit the throttle mediator policy by clicking the Throttle Policy Editor under In-Lined Policy, the pop-up doesn't load with the correct content.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by Nirothipan** [comment] 2018-04-04 16:11
Duplicate of https://wso2.org/jira/browse/ESBJAVA-5283

**Closed by Nirothipan** 2018-04-04 16:11 UTC
Labels: Resolution/Duplicate
