### ISSUE TITLE
NPE in Calling An External Service (Send/Connector) After Receiving a Message From a JMS Store/Processor

### ISSUE THREAD

**Issue by lafernando** [wso2/product-ei#524] opened 2017-04-09 07:51 UTC
Steps to reproduce:-

* Create a JMS message store using WSO2 MB
* Create a Message Sampling Processor which links to the earlier created message store and sends it to a sequence
* In the sequence, call an external service (e.g. data service) or invoke a connector (e.g. JIRA issue create)
* Create a scheduled task to add a message to the message store
* When the final sequence is running, you will see some NPE errors, similar to: https://pastebin.com/kYjzcv3L

A quick debug showed that, this seems to be occurring in the code due to Axis2 level OperationContext references seems to be null when going through a flow like the above. I was able to get the flow working successfully, after simply doing null checks and ignoring the operations related to OperationContexts. Multiple places were required in synapse-core was required to fix it. This has to be properly investigated and fixed.

**Comment by nandika** [comment] 2017-04-09 16:03
at java.lang.Thread.run(Thread.java:745)
[2017-04-06 08:10:19,105] [EI-Core] ERROR - MessageConverter Cannot create Message Context. Error:null
java.lang.NullPointerException
	at org.apache.synapse.message.store.impl.commons.MessageConverter.toMessageContext(MessageConverter.java:131)
	at org.apache.synapse.message.store.impl.jms.JmsConsumer.receive(JmsConsumer.java:107)
	at org.apache.synapse.message.processor.impl.sampler.SamplingService.fetch(SamplingService.java:188)
	at org.apache.synapse.message.processor.impl.sampler.SamplingService.execute(SamplingService.java:120)
	at org.wso2.carbon.mediation.ntask.NTaskAdapter.execute(NTaskAdapter.java:98)
	at org.wso2.carbon.ntask.core.impl.TaskQuartzJobAdapter.execute(TaskQuartzJobAdapter.java:67)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[2017-04-06 08:10:20,107] [EI-Core] ERROR - MessageConverter Cannot create Message Context. Error:null
java.lang.NullPointerException
	at org.apache.synapse.message.store.impl.commons.MessageConverter.toMessageContext(MessageConverter.java:131)
	at org.apache.synapse.message.store.impl.jms.JmsConsumer.receive(JmsConsumer.java:107)
	at org.apache.synapse.message.processor.impl.sampler.SamplingService.fetch(SamplingService.java:188)
	at org.apache.synapse.message.processor.impl.sampler.SamplingService.execute(SamplingService.java:120)
	at org.wso2.carbon.mediation.ntask.NTaskAdapter.execute(NTaskAdapter.java:98)
	at org.wso2.carbon.ntask.core.impl.TaskQuartzJobAdapter.execute(TaskQuartzJobAdapter.java:67)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

Copying the exception from pastbin to git issues

**Comment by nandika** [comment] 2017-04-09 16:04
What is the EI version and synapse version. 
If you already have a fix, will you be able to provide a diff

**Comment by lafernando** [comment] 2017-04-10 03:14
Hi Nandika,

It's EI 6.0. And sure, I'm attaching the local fix I did, but it has to be validated to see if it's a correct fix. I blindly just ignored the operations done for the "OperationContext" objects.

Cheers,
Anjana.
[synapse-patch.txt](https://github.com/wso2/product-ei/files/908894/synapse-patch.txt)

**Comment by lafernando** [comment] 2017-04-11 17:35
Hi,

Can this please be marked as a bug and a blocker. This must be fixed for v6.1.0.

Cheers,
Anjana.

**Comment by prabushi** [comment] 2017-04-18 07:34
Hi Anjana,
I tried to reproduce this issue following the steps you have mentioned above. Still I couldn't reproduce this issue. 
When you say "When the final sequence is running, you will see some NPE errors, similar to: ", Is there another sequence, other than the sequence defined in the message store?
Could you please provide a sample configuration if you have one?

Thanks,
Prabushi

**Comment by prabushi** [comment] 2017-04-19 04:40
Similar issue: https://wso2.org/jira/browse/ESBJAVA-5051

**Comment by sdkottegoda** [comment] 2019-04-18 05:19
Fixed by the resolution for https://wso2.org/jira/browse/ESBJAVA-5051

**Closed by sdkottegoda** 2019-04-18 05:19 UTC
