### ISSUE TITLE
[Critical] Mediation Debugger broken

### ISSUE THREAD

**Issue by dushansachinda** [wso2/product-ei#128] opened 2017-02-06 02:37 UTC

**Comment by dushansachinda** [comment] 2017-02-10 07:21
Mediation debugger not working correctly, sometimes break points not saving. Most often debugger not working. Please contact me before proceeding I will showcase the scenario

**Comment by pumudu88** [comment] 2017-02-17 06:25
To resolve this issue follow the steps bellow.

- Restart eclipse.

- "Resend ESB Breakpoints" once ESB started(with debugging) from eclipse design view.

<img src="https://cloud.githubusercontent.com/assets/8552767/23054653/40854128-f507-11e6-8b09-b3ee1dc995d7.jpg" width="300">

**Comment by balajisetty** [comment] 2017-05-25 20:18
I tried all possible ways to enable debug. It's still broken !!!

**Comment by pumudu88** [comment] 2017-05-26 02:36
@balajisetty can you please provide exact EI/tooling versions you attempt and steps to reproduce? Did you tried to "Resend ESB breakpoints" as mentioned in above comment?

**Comment by balajisetty** [comment] 2017-05-26 17:58
EI is 6.1.1 and tooling is Mars.2 

Yes i tried to resend ESB breakpoints as mentioned in comments of another issue

**Comment by madhawa-gunasekara** [comment] 2018-01-17 03:14
Closing this issue, Since this has been fixed with latest dev studio tooling

**Comment by SupunS** [comment] 2018-01-27 18:27
Reopening the issue, since the same issue is encountered for me as well, on EI Tooling  6.1.1 (Mars2).
Tried to debug the sample API at \[1\], but the debug points are not hitting at all. Tried restarting the server + debugger, and also resending the breakpoints, but no luck.

\[1\] https://docs.wso2.com/display/EI611/Exposing+Several+Services+as+a+Single+Service

**Comment by prabushi** [comment] 2018-02-01 15:54
Issue has occurred when the HTTP methods are not defined for that particular API resource. When methods are empty, it does not match with the HTTP method that we used to invoke that particular resource. Hence the breakpoints are not getting hit.

Created https://github.com/wso2/product-ei/issues/1815 to incorporate HTTP method validation for API resource at CApp deployment to avoid such issues.

**Closed** 2018-02-01 15:54 UTC
Labels: Fixed, Priority/High, Severity/Critical, Type/Bug
