### ISSUE TITLE
Old version of SAP transport is packed with the distribution

### ISSUE THREAD

**Issue by ThishaniLucas** [wso2/product-ei#2492] opened 2018-07-31 07:29 UTC
**Description:**
The SAP transport jar version should be the latest carbon mediation version 4.6.*. But still the org.wso2.carbon.transports.sap_1.0.0.jar is packed with the product. Therefore, bug fixes and improvements done to the SAP transport are not available in the product.

**Related Issues:**
https://wso2.org/jira/browse/ESBJAVA-5306

**Comment by Nirothipan** [comment] 2019-03-13 13:19
duplicate of https://github.com/wso2/product-ei/issues/870

**Closed by Nirothipan** 2019-03-13 13:19 UTC
