### ISSUE TITLE
automatic string to int convertion after use of transformation (BUG)

### ISSUE THREAD

**Issue by Neros22** [wso2/product-ei#4364] opened 2019-07-08 07:34 UTC
**Description:**
When a json request is sent and the payload includes string elements, somehow the strings are converted to integer type in the response. I have tried to fix this by adding "@@@" in the transform file infront of the elements that needs to stay as string type. This issue was fixed in the version 6.5.0 but is it possible to add this bug fix into WSO2 EI 6.4.0 as I cannot upgrade to the newest version at the very moment.

**Affected Product Version: **
WSO2 EI 6.4.0

**Comment by arunans23** [comment] 2019-07-15 09:02
@Neros22 Can you mention the synapse configuration you are using? It is impossible to say how the elements are getting converted without looking at the Synapse Configuration.

Also please note that, unless you have an [active WUM subscription](https://wso2.com/updates/wum) it is not possible to get a fix in 6.4.0.

**Comment by GDLMadushanka** [comment] 2019-12-02 11:20
Closing the issue since the issue is fixed in the latest version and it needs a subscription to get new fixes.

**Closed by GDLMadushanka** 2019-12-02 11:20 UTC

**Comment by keremcankabadayi** [comment] 2019-12-19 13:36
@GDLMadushanka Hi! Which version have you mentioned? Or can you share PR number?

**Comment by GDLMadushanka** [comment] 2019-12-20 00:29
> @GDLMadushanka Hi! Which version have you mentioned? Or can you share PR number?

6.6.0 (will be released soon) or 6.5.0 (WUM update)
