### ISSUE TITLE
Invoking REST api PATCH resource without message body fails

### ISSUE THREAD

**Issue by uvindra** [wso2/product-ei#3310] opened 2019-03-07 05:02 UTC
**Description:**
When doing a PATCH request on a REST api resource without a message body, the request does not get forwarded to the corresponding backend URL resource but instead gets forwarded to the root backend URL.

Example:  
Resource is - /resource

REST api URL is - http://rest-api

Back end URL is - http://backend-service

API invocation - curl -v -X PATCH "http://rest-api/resource"

Note that since there is no message body, no content type is specified. The call is expected to be forwarded to the following backend URL,

http://backend-service/resource

However it gets forwarded to the root backend URL without the resource as,

http://backend-service

**Suggested Labels:**
Bug

**Suggested Assignees:**

**Affected Product Version:**
APIM 2.2.0, EI 6.2.0

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by nandika** [comment] 2019-03-25 05:12
The fixed is merged and confirmed with Uvindra.

**Comment by sdkottegoda** [comment] 2019-03-25 05:12
Closing since https://github.com/wso2/wso2-synapse/pull/1266 is merged

**Closed** 2019-03-25 05:12 UTC
Labels: 6.5.0
