### ISSUE TITLE
[EI61][DSS][Oracle] Exception when inserting data to a table using odata

### ISSUE THREAD

**Issue by sashikamw** [wso2/product-ei#347] opened 2017-03-23 17:06 UTC
**Environment**
OS -ubuntu 15.10
JAVA -jdk 1.7.0_65
Browser-chrome version 53.0.2785.89
EI610 PreAlpha Pack
DB - postgresSQL

**Steps**
1. Create a table with primary key
ex: 
CREATE TABLE People (
    ID int NOT NULL PRIMARY KEY,
    LastName varchar(255) NOT NULL,
    FirstName varchar(255),
    Age int
);
2. Create a data service with odata enabled
3. Use http POST to add data row

**Observation**
1. Data added to the table
2. Following return as the response

```
{
"error": {
"code": null,
"message": "Error occurred. :Error occurred while creating entity. :The value '11' does not match the facets' constraints."
}
}

```
3. Following error observed in terminal
```
TID: [-1234] [] [2017-03-23 22:16:13,697] ERROR {org.wso2.carbon.dataservices.core.odata.ODataAdapter} -  Error occurred. :Error occurred while creating entity. :The value '11' does not match the facets' constraints. {org.wso2.carbon.dataservices.core.odata.ODataAdapter}
org.apache.olingo.server.api.ODataApplicationException: Error occurred while creating entity. :The value '11' does not match the facets' constraints.
	at org.wso2.carbon.dataservices.core.odata.ODataAdapter.createEntity(ODataAdapter.java:410)
	at org.apache.olingo.server.core.requests.DataRequest$EntityRequest.execute(DataRequest.java:359)
	at org.apache.olingo.server.core.requests.DataRequest.execute(DataRequest.java:255)
	at org.apache.olingo.server.core.ServiceDispatcher.internalExecute(ServiceDispatcher.java:160)
	at org.apache.olingo.server.core.ServiceDispatcher.execute(ServiceDispatcher.java:98)
	at org.apache.olingo.server.core.OData4HttpHandler.process(OData4HttpHandler.java:67)
	at org.wso2.carbon.dataservices.core.odata.ODataServiceHandler.process(ODataServiceHandler.java:80)
	at org.wso2.carbon.dataservices.odata.endpoint.ODataEndpoint.process(ODataEndpoint.java:71)
	at org.wso2.carbon.dataservices.odata.ODataServlet.service(ODataServlet.java:31)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:218)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:110)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:615)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:99)
	at org.wso2.carbon.tomcat.ext.valves.CarbonTomcatValve$1.invoke(CarbonTomcatValve.java:47)
	at org.wso2.carbon.webapp.mgt.TenantLazyLoaderValve.invoke(TenantLazyLoaderValve.java:57)
	at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:47)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:62)
	at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:159)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:962)
	at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:57)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:452)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1087)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:637)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1760)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1719)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by sashikamw** [comment] 2017-04-07 12:52
This issue is reproducible in the snapshot shared on 07/04/2017 with patch consists of following jars.
org.wso2.carbon.core_4.4.15.jar
org.wso2.carbon.dataservices.core_4.4.5.jar
org.wso2.carbon.integrator.core_6.1.0-SNAPSHOT.jar


payload
Content-type - application/json
```
{
"LASTNAME": "saml",
"FIRSTNAME": "naa",
"ID": 19,
"AGE": 22
}

```

**Comment by Jame-Chen** [comment] 2018-06-22 05:49
@sashikamw ,Can't find the jar package version you mentioned and can send it to my gmail mailbox?
Jamechen931863353@gmail.com

**Comment by Vathsan** [comment] 2019-04-17 10:56
Could not reproduce the issue in 6.5.0-m5 pack. POST request works fine with OData services. 

When executing the curl command, curl performs SSL certificate verification by default. Use the -k (or --insecure) option to turn off curl's verification.
Sample curl command to read details from a table would be,
`curl -k -X GET -H 'Accept: application/xml' https://localhost:9443/odata/{data_service_name}/{data_source_id}/{table_name}`

**Comment by sdkottegoda** [comment] 2019-04-17 12:42
Closing since the issue is not reproducible.

**Closed by sdkottegoda** 2019-04-17 12:42 UTC
Labels: Severity/Critical, Type/Bug
