### ISSUE TITLE
Incorrect debug log printed in VFS Listener

### ISSUE THREAD

**Issue by jagathsisira** [wso2/product-ei#543] opened 2017-04-25 08:43 UTC
Incorrect log entry is printed at VFS Proxy deployment with secure vault credentials used. It should be corrected at [1][2] to print the log only if parameters are missing. Now it is printed even correct parameters are available.

[1] - https://github.com/wso2/wso2-synapse/blob/master/modules/commons/src/main/java/org/apache/synapse/commons/crypto/Util.java#L47
[2] - https://github.com/wso2/wso2-synapse/blame/master/modules/securevault/src/main/java/org/apache/synapse/securevault/secret/SecretManager.java#L256

**Comment by pamod** [comment] 2017-08-29 06:22
The issue is fixed with PR [1]

[1] https://github.com/wso2/wso2-synapse/pull/809/files

**Closed by pamod** 2017-08-29 06:22 UTC
