### ISSUE TITLE
not able to start axis2server.bat in EI

### ISSUE THREAD

**Issue by dhayalani** [wso2/product-ei#555] opened 2017-05-05 06:29 UTC
Getting below error while starting axis2server.bat file in EI (followed document).

C:\projects\work\BNYMASSETMGTDEV-2\wso2ei-6.1.0\samples\axis2Server>axis2server.bat
"Starting Sample Axis2 Server ..."
Using AXIS2_HOME:        C:\projects\work\BNYMAS~1\WSO2EI~1.0\samples\AXIS2S~1\
Using JAVA_HOME:       C:\Program Files\Java\jdk1.7.0
Server could not start due to class loading issue java.lang.NoSuchMethodException: samples.util.SampleAxis2Server.startServer([Ljava.lang.String;)

[1]. https://docs.wso2.com/display/EI600/Setting+Up+the+Service+Bus+Samples

**Comment by himasha** [comment] 2017-08-28 08:16
Duplicate of https://github.com/wso2/product-ei/issues/570.

**Closed by himasha** 2017-08-28 08:16 UTC
