### ISSUE TITLE
[Docs] CXF WS-RM Inbound Protocol - Broken Link

### ISSUE THREAD

**Issue by menuka94** [wso2/product-ei#4009] opened 2019-05-14 05:32 UTC
**Description:**
In the [documentation for CXF WS-RM Inbound Protocol](https://docs.wso2.com/display/EI6xx/CXF+WS-RM+Inbound+Protocol), the link for **Installing Features** is invalid.

It is not possible to try out the rest of the documentation as installing the CXF WS Reliable Messaging feature is a required step.

**Comment by Nirothipan** [comment] 2019-05-15 16:51
Duplicate of https://github.com/wso2/product-ei/issues/3901

**Closed by Nirothipan** 2019-05-15 16:51 UTC
Labels: 6.5.0, Type/Docs
