### ISSUE TITLE
[EI61][DSS][Intermittent] Service deployment failed after enabling batch request

### ISSUE THREAD

**Issue by sashikamw** [wso2/product-ei#466] opened 2017-04-01 20:15 UTC
**Environment**
OS -ubuntu 15.10
JAVA -jdk 1.7.0_65
Browser-chrome version 53.0.2785.89
EI610 Alpha Pack + patch for odata
DB - mssql
(Observed in the cluster as well)

**Steps**
1. Upload a dataservice
2. Then enable batchrequest option for the data service

[mysqltestexception.dbs.zip](https://github.com/wso2/product-ei/files/887926/mysqltestexception.dbs.zip)

**Observation**
observed nullpoint exception and the service become faulty.

```
[2017-04-02 01:38:09,813] [EI-Core]  INFO - DeploymentInterceptor Removing Axis2 Service: mysqltestexception {super-tenant}
[2017-04-02 01:38:10,453] [EI-Core] ERROR - DBDeployer The mysqltestexcepioj.dbs service, which is not valid, caused {1}
DS Fault Message: Error in creating ConfigurationBasedAuthenticator: null
DS Code: UNKNOWN_ERROR
Source Data Service:-
Name: mysqltestexception
Location: /mysqltestexcepioj.dbs
Description: N/A
Default Namespace: http://ws.wso2.org/dataservice
Nested Exception:-
java.lang.NullPointerException

	at org.wso2.carbon.dataservices.core.auth.ConfigurationBasedAuthenticator.<init>(ConfigurationBasedAuthenticator.java:55)
	at org.wso2.carbon.dataservices.core.description.config.SQLConfig.processDynamicAuth(SQLConfig.java:95)
	at org.wso2.carbon.dataservices.core.description.config.SQLConfig.<init>(SQLConfig.java:78)
	at org.wso2.carbon.dataservices.core.JDBCPoolSQLConfig.<init>(JDBCPoolSQLConfig.java:52)
	at org.wso2.carbon.dataservices.core.description.config.RDBMSConfig.<init>(RDBMSConfig.java:40)
	at org.wso2.carbon.dataservices.core.description.config.ConfigFactory.getRDBMSConfig(ConfigFactory.java:92)
	at org.wso2.carbon.dataservices.core.description.config.ConfigFactory.createConfig(ConfigFactory.java:60)
	at org.wso2.carbon.dataservices.core.DataServiceFactory.createDataService(DataServiceFactory.java:159)
	at org.wso2.carbon.dataservices.core.DBDeployer.createDBService(DBDeployer.java:797)
	at org.wso2.carbon.dataservices.core.DBDeployer.processService(DBDeployer.java:1152)
	at org.wso2.carbon.dataservices.core.DBDeployer.deploy(DBDeployer.java:201)
	at org.apache.axis2.deployment.repository.util.DeploymentFileData.deploy(DeploymentFileData.java:136)
	at org.apache.axis2.deployment.DeploymentEngine.doDeploy(DeploymentEngine.java:807)
	at org.apache.axis2.deployment.repository.util.WSInfoList.update(WSInfoList.java:144)
	at org.apache.axis2.deployment.RepositoryListener.update(RepositoryListener.java:377)
	at org.apache.axis2.deployment.RepositoryListener.checkServices(RepositoryListener.java:254)
	at org.apache.axis2.deployment.RepositoryListener.startListener(RepositoryListener.java:371)
	at org.apache.axis2.deployment.scheduler.SchedulerTask.checkRepository(SchedulerTask.java:59)
	at org.apache.axis2.deployment.scheduler.SchedulerTask.run(SchedulerTask.java:67)
	at org.wso2.carbon.core.deployment.CarbonDeploymentSchedulerTask.runAxisDeployment(CarbonDeploymentSchedulerTask.java:93)
	at org.wso2.carbon.core.deployment.CarbonDeploymentSchedulerTask.run(CarbonDeploymentSchedulerTask.java:138)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at org.wso2.carbon.dataservices.core.auth.ConfigurationBasedAuthenticator.<init>(ConfigurationBasedAuthenticator.java:50)
	... 27 more
[2017-04-02 01:38:10,454] [EI-Core]  INFO - DeploymentEngine org.apache.axis2.deployment.DeploymentException: The mysqltestexcepioj.dbs service, which is not valid, caused {1}
```

**Note** - This behaviour observed only in this service

**Comment by madhawa-gunasekara** [comment] 2017-04-02 06:35
We have to fix this NPE, but the root cause for this issue is enabling dynamic auth mapping. 

<property name="dataSourceProps"/>
<property name="dynamicUserAuthMapping"/>

**Comment by prabushi** [comment] 2017-04-03 11:17
Fixed in https://github.com/wso2/carbon-data/pull/143

**Closed** 2017-04-04 12:53 UTC
