### ISSUE TITLE
Error for specific API (Could not save JSON payload)

### ISSUE THREAD

**Issue by SiluniPathirana** [wso2/product-ei#1680] opened 2018-01-09 09:20 UTC
**Description:**

When trying to invoke an API PUT resource without passing a body. And getting a request timeout. The issue has been reproduced by using content-aware message mediators.

PUT /platform/enabler/re/rule/1.0.0/test3878252/start HTTP/1.1
Authorization: Bearer XXXXXXXXXXXXXXXXXXXXXXX
Content-Length: 0

**Suggested Labels:**
Type/Bug 

**Suggested Assignees:**

**Affected Product Version:**
API Manager 2.1.0, EI 6.1.1,Type/Bug ,Priority/High

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
1. Create API  with content-aware message mediators in synapse config.
2.  Invoke PUT resource without passing a body

**Related Issues:**
https://github.com/wso2/product-apim/issues/2291

**Comment by madhawa-gunasekara** [comment] 2018-01-16 05:24
Hi @SiluniPathirana,

Since This issue is not reproducable with EI 6.x.x. I'm closing this issue, We are not recommending to use OLD JSON Message builders and formatters with EI, and also this issue should be opened in APIM project. and also This issue will fix once APIM have moved to latest JSON message builders and formatters.

https://wso2.org/jira/browse/APIMANAGER-5529

**Closed by madhawa-gunasekara** 2018-01-16 05:24 UTC
Labels: Severity/Blocker
