### ISSUE TITLE
Adding Address endpoint templates broken

### ISSUE THREAD

**Issue by isudana** [wso2/product-ei#4006] opened 2019-05-13 23:48 UTC
1. Add an endpoint with name = $name and address = $uri.
2. Switch to source view
3. Switch back to design view

Getting following

[2019-05-13 17:29:14,461] [EI-Core] ERROR - ApplicationDispatcher Servlet.service() for servlet bridgeservlet threw exception
org.apache.synapse.config.xml.endpoints.resolvers.ResolverException: Resolver could not be found
	at org.apache.synapse.config.xml.endpoints.resolvers.ResolverFactory.getResolver(ResolverFactory.java:83)
	at org.apache.synapse.config.xml.endpoints.AddressEndpointFactory.createEndpointDefinition(AddressEndpointFactory.java:124)
	at org.apache.synapse.config.xml.endpoints.AddressEndpointFactory.createEndpoint(AddressEndpointFactory.java:89)
	at org.apache.synapse.config.xml.endpoints.EndpointFactory.createEndpointWithName(EndpointFactory.java:143)
	at org.apache.synapse.config.xml.endpoints.EndpointFactory.getEndpointFromElement(EndpointFactory.java:99)
	at org.wso2.carbon.endpoint.ui.endpoints.address.AddressEndpoint.build(AddressEndpoint.java:509)
	at org.apache.jsp.endpoints.forms.addressEndpoint_002dform_jsp._jspService(addressEndpoint_002dform_jsp.java:272)
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:472)
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:395)
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:339)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)

**Comment by Nirothipan** [comment] 2019-05-14 00:09
This has happened due to 
`Caused by: org.apache.synapse.config.xml.endpoints.resolvers.ResolverException: Resolver could not be found`
Same cause as in https://github.com/wso2/product-ei/issues/4001.
This is fixed with https://github.com/wso2/wso2-synapse/pull/1346

**Closed by Nirothipan** 2019-05-14 00:09 UTC
Labels: Severity/Blocker
