### ISSUE TITLE
Intermittent issue occurs when viewing the poison message received to the message processor

### ISSUE THREAD

**Issue by dulanjalidilmi** [wso2/product-ei#4985] opened 2020-02-25 06:34 UTC
**Description:**
When the user tries to view the received poison message on the message processor, intermittently "Subscribed Queue is Empty" message will be displayed as followed.
<img width="449" alt="Screenshot 2020-02-25 at 11 55 22" src="https://user-images.githubusercontent.com/38608578/75220908-94371380-57c6-11ea-9edb-782129f735c0.png">
. 

**Affected Product Version:**
EI. 6.4.0

**Steps to reproduce:**

1. Send poison messaged until the message processor gets deactivated
2. Click on the "view message" button of message processor.
3. Intermittently the message would display as "Subscribed Queue is Empty"

**Related Issues:**
 wso2/product-ei#3670

**Comment by dilini-muthumala** [comment] 2021-07-13 09:15
Closing the issue as the issue is fixed with https://github.com/wso2/wso2-synapse/commit/5e35203194c5e9c92c515d15365b58a15fd5e372

**Closed by dilini-muthumala** 2021-07-13 09:15 UTC
