### ISSUE TITLE
[EI61][DSS] POST method in the JSON sample failed due to "INCOMPATIBLE_PARAMETERS_ERROR"

### ISSUE THREAD

**Issue by sashikamw** [wso2/product-ei#368] opened 2017-03-26 14:54 UTC
**Environment**
OS - ubuntu 15.10
JAVA -jdk 1.7
EI610 PreAlpha Pack
DB - Postgres/H2
dataservice - jsonsample.dbs

**Steps**
deploy the JSON sample and execute the POST method as mentioned in the document [1] 

Note - Accept and content-type header added

**Observation**
Following exception observed when invoking the POST method using a rest client

```
{
"Fault": {
"faultcode": "axis2ns9:INCOMPATIBLE_PARAMETERS_ERROR",
"faultstring": "DS Fault Message: Error in DS non result invoke. DS Code: INCOMPATIBLE_PARAMETERS_ERROR Nested Exception:- javax.xml.stream.XMLStreamException: DS Fault Message: Error in 'CallQuery.extractParams', cannot find parameter with type:query-param name:lastName DS Code: INCOMPATIBLE_PARAMETERS_ERROR Source Data Service:- Name: JSONSample Location: /samples/JSONSample.dbs Description: N/A Default Namespace: http://ws.wso2.org/dataservice/samples/json_sample Current Request Name: _postemployee Current Params: {} ",
"detail": ""
}
}
```

```
[2017-03-26 20:10:27,565] [EI-Core] ERROR - DBInOnlyMessageReceiver Error in in-only message receiver
DS Fault Message: Error in DS non result invoke.
DS Code: INCOMPATIBLE_PARAMETERS_ERROR
Nested Exception:-
javax.xml.stream.XMLStreamException: DS Fault Message: Error in 'CallQuery.extractParams', cannot find parameter with type:query-param name:lastName
DS Code: INCOMPATIBLE_PARAMETERS_ERROR
Source Data Service:-
Name: JSONSample
Location: /samples/JSONSample.dbs
Description: N/A
Default Namespace: http://ws.wso2.org/dataservice/samples/json_sample
Current Request Name: _postemployee
Current Params: {}


	at org.wso2.carbon.dataservices.core.dispatch.SingleDataServiceRequest.processSingleRequest(SingleDataServiceRequest.java:118)
	at org.wso2.carbon.dataservices.core.dispatch.SingleDataServiceRequest.processRequest(SingleDataServiceRequest.java:67)
	at org.wso2.carbon.dataservices.core.dispatch.DataServiceRequest.dispatch(DataServiceRequest.java:354)
	at org.wso2.carbon.dataservices.core.DataServiceProcessor.dispatch(DataServiceProcessor.java:41)
	at org.wso2.carbon.dataservices.core.DBInOnlyMessageReceiver.invokeBusinessLogic(DBInOnlyMessageReceiver.java:53)
	at org.apache.axis2.receivers.AbstractMessageReceiver.receive(AbstractMessageReceiver.java:110)
	at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180)
	at org.apache.synapse.transport.passthru.ServerWorker.processNonEntityEnclosingRESTHandler(ServerWorker.java:326)
	at org.apache.synapse.transport.passthru.ServerWorker.processEntityEnclosingRequest(ServerWorker.java:372)
	at org.apache.synapse.transport.passthru.ServerWorker.run(ServerWorker.java:151)
	at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

```
Note - This works file with DSS351 when sending the payload without double quotes for empnumber and salary.
{
  "_postemployee": {
    "employeeNumber" : 14008,
    "lastName": "Smith",
    "firstName": "Will",
    "email": "will@google.com",
    "salary": 15500.0
  }
}

[1] https://docs.wso2.com/display/EI600/JSON+Mapping+Sample

**Comment by VijithaEkanayake** [comment] 2017-03-26 15:09
This is fixed in latest code with following PR : https://github.com/wso2/product-ei/pull/362

**Comment by VijithaEkanayake** [comment] 2017-03-31 10:27
Tested JSON Samples in the ALPHA pack as well in the latest build. The issue is fixed with https://github.com/wso2/product-ei/pull/362

**Closed by VijithaEkanayake** 2017-03-31 10:27 UTC
Labels: bug, critical, Fixed
