### ISSUE TITLE
Enrich Mediator JSON support 

### ISSUE THREAD

**Issue by kasun04** [wso2/product-ei#3659] opened 2019-04-09 00:31 UTC
Add JSON support related improvement which is already done(?) to runtime and tooling.

**Comment by dilee** [comment] 2019-04-29 05:38
The fix has been done but not yet merged since we're currently investigating a potential regression caused by the Gson library.

**Comment by dilee** [comment] 2019-04-30 03:38
This has been fixed.

**Closed by dilee** 2019-04-30 03:38 UTC
Labels: Component/Integrator, EI Tooling, Severity/Blocker
