### ISSUE TITLE
ERROR - JsonUtil #newJsonPayload when accessing registry payloads with extention .json

### ISSUE THREAD

**Issue by isudana** [wso2/product-ei#4294] opened 2019-06-14 02:13 UTC
**Description:**
This issue is originally reported by Asanthi Kulasinghe at 
https://wso2.org/jira/browse/ESBJAVA-4313

Upload the attached json3.json file to registry.
Deploy and invoke proxy service [1].

The following error occurs .

[2015-11-12 14:30:44,864] ERROR - JsonUtil #newJsonPayload. Could not save JSON payload. Invalid input stream found. MessageID: urn:uuid:284c9071-620f-4e9d-b061-808e0007d9e5

This is not reproducible if the payload file is uploaded with the extention.txt.

`<proxy name="CustomerServiceProxy_json"
          transports="https http"
          startOnLoad="true"
          trace="disable">
      <description/>
      <target>
         <inSequence>
            <switch source="$axis2:HTTP_METHOD">
               <case regex="GET">
                  <property name="HTTP_METHOD" value="GET" scope="axis2" type="STRING"/>
               </case>
               <case regex="POST">
                  <property name="HTTP_METHOD" value="POST" scope="axis2" type="STRING"/>
               </case>
               <default/>
            </switch>
            <payloadFactory media-type="json">
               <format key="conf:/json3.json"/>
               <args/>
            </payloadFactory>
            <send>
               <endpoint>
                  <address uri="http://localhost:9773/jaxrs_basic/services/customers/customerservice/"/>
               </endpoint>
            </send>
         </inSequence>
         <outSequence>
            <send/>
         </outSequence>
      </target>
   </proxy>`

[json3.json.txt](https://github.com/wso2/product-ei/files/3288741/json3.json.txt)

**OS, DB, other environment details and versions:**    
Ubuntu 13.04
JDK 1.7

**Related Issues:**
https://wso2.org/jira/browse/ESBJAVA-4313

**Comment by GDLMadushanka** [comment] 2019-11-20 08:08
Closing since cannot reproduce with the latest versions

**Closed by GDLMadushanka** 2019-11-20 08:08 UTC
Labels: Priority/Normal, Type/Bug
