### ISSUE TITLE
[BPMN explorer] process monitoring does not show process details

### ISSUE THREAD

**Issue by Kishanthan** [wso2/product-ei#270] opened 2017-03-06 10:11 UTC
Running the LoanApprovalProcess in EI 6.0.

The process monitoring / filter does not show any data / variable information for processes that are searched/filtered. Check the below screenshot. Check the process details section which is shown empty for a particular process.
<img width="1131" alt="screen shot 2017-03-06 at 3 35 14 pm" src="https://cloud.githubusercontent.com/assets/690559/23605545/2ab1194c-0283-11e7-866c-f20da630d872.png">

**Comment by Kishanthan** [comment] 2017-03-06 10:15
This looks like a browser specific issue. The same works fine in chrome where I could see the results. But it does not work in Safari.

**Comment by vinok88** [comment] 2017-03-06 10:23
I checked this in Safari also. Works for me in Safari 10.0.3.

**Comment by vinok88** [comment] 2017-03-09 07:06
Closing the issue since this is not reproducible.

**Closed by vinok88** 2017-03-09 07:06 UTC
Labels: UI
