### ISSUE TITLE
 JMS Inbound Endpoint is not suspended while updating through the management console

### ISSUE THREAD

**Issue by KasunAratthanage** [wso2/product-ei#4066] opened 2019-05-22 06:41 UTC
**Description:**
JMS Inbound Endpoint is not suspended while updating through the management console.(Not using car applications)

**Suggested Labels:**
JMS Inbound Protocol

**Affected Product Version:**
EI - 6.5.0

**OS, DB, other environment details and versions:**    
Ubuntu

**Steps to reproduce:**

Set up WSO2 MB with the WSO2 EI - 6.5.0.
Create a JMS inbound endpoint using the EI management console.
Publish a message using the MB.
Check the console output from the EI.

Actual output - Print the published messages.
Expected output - Print the published messages.    

Edit JMS inbound endpoint properties via the UI ( Suspended= true).
Update and save (EI console output ---> print message as "inbound endpoint is suspended").
Publish a message using the MB.
Check the console output from the EI.

Actual output - Print the published messages.  
Expected output - Not Print the published messages.

**Comment by malakaganga** [comment] 2019-11-22 05:54
Could not reproduce hence resolving the issue

**Closed by malakaganga** 2019-11-22 05:54 UTC
Labels: 6.6.0
