### ISSUE TITLE
When there is a conversion of back-end json response to soap, an empty envelope is written back to the client

### ISSUE THREAD

**Issue by Manuri** [wso2/product-ei#1323] opened 2017-11-15 10:20 UTC
**Description:**
When there is a conversion of back-end json response to soap, an empty envelope is written back to the client. Later when trying to write the actual response, following exception occurs.

`org.apache.axis2.AxisFault: Failed to submit the response
	at org.apache.synapse.transport.passthru.PassThroughHttpSender.handleException(PassThroughHttpSender.java:632)
	at org.apache.synapse.transport.passthru.PassThroughHttpSender.invoke(PassThroughHttpSender.java:266)
	at org.apache.axis2.engine.AxisEngine.send(AxisEngine.java:442)
	at org.apache.synapse.core.axis2.Axis2Sender.sendBack(Axis2Sender.java:230)
	at org.apache.synapse.core.axis2.Axis2SynapseEnvironment.send(Axis2SynapseEnvironment.java:531)
	at org.apache.synapse.mediators.builtin.SendMediator.mediate(SendMediator.java:118)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:97)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:59)
	at org.apache.synapse.mediators.base.SequenceMediator.mediate(SequenceMediator.java:158)
	at org.apache.synapse.core.axis2.Axis2SynapseEnvironment.injectMessage(Axis2SynapseEnvironment.java:337)
	at org.apache.synapse.core.axis2.SynapseCallbackReceiver.handleMessage(SynapseCallbackReceiver.java:554)
	at org.apache.synapse.core.axis2.SynapseCallbackReceiver.receive(SynapseCallbackReceiver.java:188)
	at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180)
	at org.apache.synapse.transport.passthru.ClientWorker.run(ClientWorker.java:262)
	at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.axis2.AxisFault: Can not output XML declaration, after other output has already been done.
	at org.apache.axis2.AxisFault.makeFault(AxisFault.java:430)
	at org.apache.axis2.transport.http.SOAPMessageFormatter.writeTo(SOAPMessageFormatter.java:78)
	at org.apache.synapse.transport.passthru.PassThroughHttpSender.submitResponse(PassThroughHttpSender.java:573)
	at org.apache.synapse.transport.passthru.PassThroughHttpSender.invoke(PassThroughHttpSender.java:264)
	... 16 more
Caused by: javax.xml.stream.XMLStreamException: Can not output XML declaration, after other output has already been done.
	at com.ctc.wstx.sw.BaseStreamWriter.throwOutputError(BaseStreamWriter.java:1522)
	at com.ctc.wstx.sw.BaseStreamWriter.reportNwfStructure(BaseStreamWriter.java:1551)
	at com.ctc.wstx.sw.BaseStreamWriter.doWriteStartDocument(BaseStreamWriter.java:650)
	at com.ctc.wstx.sw.BaseStreamWriter.writeStartDocument(BaseStreamWriter.java:638)
	at com.ctc.wstx.sw.BaseStreamWriter.writeStartDocument(BaseStreamWriter.java:626)
	at org.apache.axiom.om.impl.MTOMXMLStreamWriter.writeStartDocument(MTOMXMLStreamWriter.java:277)
	at org.apache.synapse.commons.json.JsonDataSource.serialize(JsonDataSource.java:88)
	at org.apache.axiom.om.impl.llom.OMSourcedElementImpl.internalSerialize(OMSourcedElementImpl.java:691)
	at org.apache.axiom.om.impl.util.OMSerializerUtil.serializeChildren(OMSerializerUtil.java:562)
	at org.apache.axiom.om.impl.llom.OMElementImpl.internalSerialize(OMElementImpl.java:875)
	at org.apache.axiom.soap.impl.llom.SOAPEnvelopeImpl.serializeInternally(SOAPEnvelopeImpl.java:283)
	at org.apache.axiom.soap.impl.llom.SOAPEnvelopeImpl.internalSerialize(SOAPEnvelopeImpl.java:245)
	at org.apache.axiom.om.impl.llom.OMSerializableImpl.serializeAndConsume(OMSerializableImpl.java:193)
	at org.apache.axis2.transport.http.SOAPMessageFormatter.writeTo(SOAPMessageFormatter.java:74)
	... 18 more
`

This error occurs as there is already an empty envelope written out. The reason why an empty envelope written out is as follows.
When backend responds with a json message, it will be processed as a Json stream. If it is not built before SOAPMessageFormatter tries to format it and write out to the client, SOAPMessageFormatter does not know in advance of the json stream but seems only an empty envelope so it writes the envelope out. Later when it access the elements inside, the full stream will get built but as the response is already written out, the above mentioned exception occurs.

A workaround to fix this is, invoke a content-aware mediator before the formatter is hit. Or, if there is not hard requirement for the response to be SOAP, can use application/xml instead of text/xml when sending the request.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
6.1.1
**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
1. Create a proxy which calls to an endpoint that sends a application/json response. In the out sequence just send the response back to the client(have a send mediator). Do not have put any content aware mediators which causes the JSON response to be built.
2. Send a POST request with text/xml content type and a SOAP envelope

**Related Issues:**

**Comment by riyafa** [comment] 2018-01-30 05:03
Same as https://github.com/wso2/product-ei/issues/414

**Comment by sdkottegoda** [comment] 2019-04-08 06:25
Closing since this is duplicated by https://github.com/wso2/product-ei/issues/414

**Comment by GDLMadushanka** [comment] 2019-11-15 04:28
This is still reproducible in EI 6.5.0 WUM updated pack. #414 address only an endpoint issue.

**Closed** 2024-10-02 18:16 UTC
Labels: Priority/High, IceBox
