### ISSUE TITLE
[Tooling] Cannot generate MI docker image for Data services 

### ISSUE THREAD

**Issue by abeykoon** [wso2/product-ei#3872] opened 2019-05-04 06:37 UTC
**Description:**

Steps to reproduce. 

1. create a data service using EI tooling with following config

```
<data name="findDoctor" serviceGroup="" serviceNamespace="">
    <description/>
    <config id="doctorInformationStore">
        <property name="org.wso2.ws.dataservice.user">wso2</property>
        <property name="org.wso2.ws.dataservice.password">wso2</property>
        <property name="org.wso2.ws.dataservice.protocol">jdbc:mysql://mysqlDataStore:3306/doctor</property>
        <property name="org.wso2.ws.dataservice.driver">com.mysql.jdbc.Driver</property>
    </config>
    <query id="queryDoctor" useConfig="doctorInformationStore">
        <sql>Select name, hospital from doctor where field=?</sql>
        <param name="field" paramType="SCALAR" sqlType="STRING" type="IN"/>
        <result element="doctor">
            <element column="name" name="name" xsdType="xs:string"/>
            <element name="hospital" xsdType="xs:string"/>
        </result>
    </query>
    <resource method="GET" path="doctor/{field}">
        <call-query href="queryDoctor">
            <with-param name="field" query-param="field"/>
        </call-query>
    </resource>
</data>
```
2. Create a Composite App project with above DS. 
3. Try to generate a docker image with it. 

<img width="1432" alt="Screen Shot 2019-05-04 at 9 41 04 AM" src="https://user-images.githubusercontent.com/4967046/57175082-18e62900-6e65-11e9-9972-c03cf33b7364.png">

**Comment by dilee** [comment] 2019-05-06 11:06
The error trace for this particular issue is as follows.

```
org.wso2.developerstudio.eclipse.esb.docker.exceptions.DockerImageGenerationException: Could not create the Docker image bundle file.
	at org.wso2.developerstudio.eclipse.esb.docker.util.DockerImageGenerator.buildImage(DockerImageGenerator.java:273)
	at org.wso2.developerstudio.eclipse.esb.docker.util.DockerImageGenerator.generateDockerImage(DockerImageGenerator.java:202)
	at org.wso2.developerstudio.eclipse.esb.docker.job.GenerateDockerImageJob.run(GenerateDockerImageJob.java:141)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
Caused by: com.spotify.docker.client.exceptions.DockerException: java.io.IOException: Cannot run program "docker-credential-osxkeychain": error=2, No such file or directory
	at com.spotify.docker.client.auth.ConfigFileRegistryAuthSupplier.authForBuild(ConfigFileRegistryAuthSupplier.java:108)
	at com.spotify.docker.client.DefaultDockerClient.build(DefaultDockerClient.java:1483)
	at com.spotify.docker.client.DefaultDockerClient.build(DefaultDockerClient.java:1460)
	at org.wso2.developerstudio.eclipse.esb.docker.util.DockerImageGenerator.buildImage(DockerImageGenerator.java:249)
	... 3 more
Caused by: java.io.IOException: Cannot run program "docker-credential-osxkeychain": error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at java.lang.Runtime.exec(Runtime.java:620)
	at java.lang.Runtime.exec(Runtime.java:450)
	at java.lang.Runtime.exec(Runtime.java:347)
	at com.spotify.docker.client.SystemCredentialHelperDelegate.exec(SystemCredentialHelperDelegate.java:140)
	at com.spotify.docker.client.SystemCredentialHelperDelegate.get(SystemCredentialHelperDelegate.java:88)
	at com.spotify.docker.client.DockerCredentialHelper.get(DockerCredentialHelper.java:119)
	at com.spotify.docker.client.DockerConfigReader.authWithCredentialHelper(DockerConfigReader.java:282)
	at com.spotify.docker.client.DockerConfigReader.authForAllRegistries(DockerConfigReader.java:166)
	at com.spotify.docker.client.auth.ConfigFileRegistryAuthSupplier.authForBuild(ConfigFileRegistryAuthSupplier.java:106)
```

This error occurs due to an issue with the Docker server installed on Mac-based operating systems. The cause for this particular issue is explained in [this issue](https://github.com/docker/for-mac/issues/2131) and can be fixed by following these steps.

1. Open _~/.docker/config.json_ file.
2. Delete the following line.
```
"credsStore" : "osxkeychain"
```
3. Restart the Docker server.

This is not an issue caused by the EI Tooling Docker generation feature.

**Closed by dilee** 2019-05-06 11:06 UTC
Labels: EI Tooling, Severity/Critical

**Comment by joaoemilio** [comment] 2019-10-29 16:58
Do you know why we DON'T get this error when generating images from command line and we DO get this error when using WSO2 Tooling?

**Comment by abeykoon** [comment] 2019-10-30 04:10
Yep, this was when we are using EI Tooling.
