### ISSUE TITLE
Sequence Template UI broken

### ISSUE THREAD

**Issue by isudana** [wso2/product-ei#3907] opened 2019-05-07 12:18 UTC
![image](https://user-images.githubusercontent.com/748819/57298603-3aa71080-70f0-11e9-9823-b383b73431a4.png)

Getting above error while saving

**Comment by Nirothipan** [comment] 2019-05-07 14:37
Duplicate of https://github.com/wso2/product-ei/issues/3844 and this is already fixed.

**Closed by Nirothipan** 2019-05-07 14:37 UTC
Labels: 6.5.0, Severity/Blocker
