### ISSUE TITLE
Aggregate on single iterate/message adds an additional layer

### ISSUE THREAD

**Issue by isurul28** [wso2/product-ei#5528] opened 2021-12-10 12:12 UTC
**Description:**
When we aggregate a message with one item there is a additional tag added to the final message.when the aggregate mediator has one payload to aggregate it will not run the the expression which we have defined in the aggregate onComplete tag.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
EI 6.6.0
**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
1. Create a iterate which will return one payload. And aggragte that payload
2. You will see that the expression defined in onComplete did not execute 

**Related Issues:**

**Comment by sachithKay** [comment] 2021-12-15 08:57
Closing this is a duplicate of https://github.com/wso2/product-ei/issues/5314

**Closed by sachithKay** 2021-12-15 08:57 UTC
