### ISSUE TITLE
Unable to rename a registry resource through Management Console

### ISSUE THREAD

**Issue by Vathsan** [wso2/product-ei#5368] opened 2021-02-23 07:11 UTC
**Description:**
When trying to rename a registry resource the following error is thrown,
![image](https://user-images.githubusercontent.com/29911181/108811975-3d7c3980-75d4-11eb-8f67-5ce9cbe20445.png)

**Suggested Labels:**
Bug

**Affected Product Version:**
EI-6.5.0, EI-6.6.0

**Steps to reproduce:**
1. Go to Carbon console > Resources > Browse > Detail view > Add Resource > Create text content and provide a name "testname"  and save
2. Click on actions and rename the created resource

**Comment by sachithKay** [comment] 2021-04-27 08:37
Closing hence this is a duplicate of: https://github.com/wso2/product-ei/issues/5415

**Closed by sachithKay** 2021-04-27 08:37 UTC
Labels: Type/Bug
