### ISSUE TITLE
Call mediator with an address endpoint fails when used within an api resource

### ISSUE THREAD

**Issue by nirmal070125** [wso2/product-ei#4562] opened 2019-08-02 03:17 UTC
**Description:**

$Title. Simply try the https://docs.wso2.com/display/EI650/Developing+Cloud+Native+Integration sample and you'll get the below error [1]. When we used 'send' mediator instead of 'call' mediator, it works.

[1]

`[2019-08-02 02:53:52,531] [micro-integrator] ERROR - ClientUtils The system cannot infer the transport information from the /forward URL.
[2019-08-02 02:53:52,533] [micro-integrator] ERROR - Axis2Sender Unexpected error during sending message out
org.apache.axis2.AxisFault: The system cannot infer the transport information from the /forward URL.
	at org.apache.axis2.description.ClientUtils.inferOutTransport(ClientUtils.java:86)
	at org.apache.synapse.core.axis2.DynamicAxisOperation$DynamicOperationClient.executeImpl(DynamicAxisOperation.java:116)
	at org.apache.axis2.client.OperationClient.execute(OperationClient.java:149)
	at org.apache.synapse.core.axis2.Axis2FlexibleMEPClient.send(Axis2FlexibleMEPClient.java:634)
	at org.apache.synapse.core.axis2.Axis2Sender.sendOn(Axis2Sender.java:85)
	at org.apache.synapse.core.axis2.Axis2SynapseEnvironment.send(Axis2SynapseEnvironment.java:569)
	at org.apache.synapse.mediators.builtin.CallMediator.handleNonBlockingCall(CallMediator.java:275)
	at org.apache.synapse.mediators.builtin.CallMediator.mediate(CallMediator.java:122)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:109)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:71)
	at org.apache.synapse.mediators.base.SequenceMediator.mediate(SequenceMediator.java:158)
	at org.apache.synapse.rest.Resource.process(Resource.java:363)
	at org.apache.synapse.rest.API.process(API.java:431)
	at org.apache.synapse.rest.RESTRequestHandler.apiProcess(RESTRequestHandler.java:135)
	at org.apache.synapse.rest.RESTRequestHandler.dispatchToAPI(RESTRequestHandler.java:113)
	at org.apache.synapse.rest.RESTRequestHandler.process(RESTRequestHandler.java:71)
	at org.apache.synapse.core.axis2.Axis2SynapseEnvironment.injectMessage(Axis2SynapseEnvironment.java:325)
	at org.apache.synapse.core.axis2.SynapseMessageReceiver.receive(SynapseMessageReceiver.java:92)
	at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180)
	at org.apache.synapse.transport.passthru.ServerWorker.processNonEntityEnclosingRESTHandler(ServerWorker.java:338)
	at org.apache.synapse.transport.passthru.ServerWorker.processEntityEnclosingRequest(ServerWorker.java:383)
	at org.apache.synapse.transport.passthru.ServerWorker.run(ServerWorker.java:152)
	at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)`

**Suggested Labels:**

Micro Integrator, Call mediator, Bug, Documentation

**Suggested Assignees:**

**Affected Product Version:**
Micro Integrator 650

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
Try this and you'll get the error;
https://docs.wso2.com/display/EI650/Developing+Cloud+Native+Integration

**Related Issues:**

**Comment by GDLMadushanka** [comment] 2019-11-19 05:19
Moved to https://github.com/wso2/micro-integrator/issues/1073

**Comment by sdkottegoda** [comment] 2019-11-27 16:22
@GDLMadushanka Why have we closed this issue?

**Comment by mtpaezmar** [comment] 2020-02-13 17:00
Hi:

I am getting thee same error using API Manager 3.1.0 Call Mediator.

Is there any solution please?

**Comment by sachithKay** [comment] 2020-06-11 11:50
Attempted to reproduce the issue with following configurations:
- Added two APIs as follows.
- Executed in VM environment.

```
<api xmlns="http://ws.apache.org/ns/synapse" name="OrderProcessApi" context="/order">
   <resource methods="POST">
      <inSequence>
         <payloadFactory media-type="json" description="order placement payload">
            <format>{    "orderDetails":$1,    "orderID":"1a23456",    "price":25.65,    "status":"successful"}</format>
            <args>
               <arg evaluator="json" expression="$"/>
            </args>
         </payloadFactory>
         <log level="full" description="order result log"/>
         <respond description="respond with order placement details"/>
      </inSequence>
      <outSequence/>
      <faultSequence/>
   </resource>
</api>
```

```
<api xmlns="http://ws.apache.org/ns/synapse" name="forwardOrderApi" context="/forward">
   <resource methods="POST">
      <inSequence>
         <call>
            <endpoint>
               <address uri="http://localhost:8280/order"/>
            </endpoint>
         </call>
         <respond/>
      </inSequence>
      <outSequence/>
      <faultSequence/>
   </resource>
</api>
```

- Called the forwardOrderApi API.
- Could not reproduce the error.
- Action was successful. 


- Please let us know if you can provide more context on the issue.

**Closed** 2024-10-02 17:13 UTC
Labels: Type/Bug, Resolution/Cannot Reproduce, IceBox
