### ISSUE TITLE
ScheduledMessageForwardingProcessor call 'reply sequence' after Connection refused

### ISSUE THREAD

**Issue by marcses** [wso2/product-ei#388] opened 2017-03-27 14:14 UTC
I have a **not** OUT_ONLY scenario with Guaranteed Delivery on HL7 messages. 
I used a ScheduledMessageForwardingProcessor to resend failed messages from messagestore.
`<messageProcessor class="org.apache.synapse.message.processor.impl.forwarder.ScheduledMessageForwardingProcessor" messageStore="JMSMS" name="Processor1" targetEndpoint="test" xmlns="http://ws.apache.org/ns/synapse">
    <parameter name="client.retry.interval">10000</parameter>
    <parameter name="max.delivery.attempts">1</parameter>
    <parameter name="member.count">1</parameter>
    <parameter name="message.processor.reply.sequence">replyLogSeq</parameter>
    <parameter name="message.processor.fault.sequence">faultLogSeq</parameter>
    <parameter name="max.delivery.drop">Disabled</parameter>
    <parameter name="interval">10000</parameter>
    <parameter name="message.processor.deactivate.sequence">deactivatedLogSeq</parameter>
    <parameter name="is.active">true</parameter>
</messageProcessor>`

If BE service is not available(es. Connection refused) the ScheduledMessageForwardingProcessor call replyLogSeq instead faultLogSeq. Is this correct?

The proxy is:
`<proxy name="testJmsHl7" startOnLoad="true" transports="hl7" xmlns="http://ws.apache.org/ns/synapse">
    <target>
        <inSequence>
            <sequence key="delivery_seq"/>
        </inSequence>
        <outSequence>
            <log level="full">
                <property name="MSG" value="in outSequence"/>
            </log>
            <send/>
        </outSequence>
        <faultSequence>
            <drop/>
        </faultSequence>
    </target>
    <parameter name="transport.hl7.maxPoolSize">400</parameter>
    <parameter name="transport.hl7.ValidateMessage">false</parameter>
    <parameter name="transport.hl7.Port">9291</parameter>
    <parameter name="transport.hl7.AutoAck">true</parameter>
    <parameter name="transport.hl7.corePoolSize">200</parameter>
    <parameter name="transport.hl7.idleThreadKeepAlive">10000</parameter>
</proxy>`

And sequences:

`<sequence name="delivery_seq" onError="delivery_fail" trace="disable" xmlns="http://ws.apache.org/ns/synapse">
    <property description="HL7_APPLICATION_ACK" name="HL7_APPLICATION_ACK" scope="axis2" type="STRING" value="false"/>
    <property name="FORCE_SC_ACCEPTED" scope="axis2" type="STRING" value="false"/>
    <property name="OUT_ONLY" scope="default" type="STRING" value="false"/>
    
    <property name="FORCE_ERROR_ON_SOAP_FAULT" scope="default" type="STRING" value="true"/>
    <enrich>
        <source clone="true" type="envelope"/>
        <target property="mssg" type="property"/>
    </enrich>
    <send>
        <endpoint key="test"/> 
    </send>
</sequence>`

`<sequence name="delivery_fail" trace="disable" xmlns="http://ws.apache.org/ns/synapse">
    <log level="full">
        <property name="MSG" value="in delivery_fail"/>
    </log>
    <enrich>
        <source clone="true" property="mssg" type="property"/>
        <target type="envelope"/>
    </enrich>
    <property name="target.endpoint" scope="default" type="STRING" value="test"/>
    <store messageStore="JMSMS"/>
</sequence>`

Log:
`[2017-03-27 16:11:38,502] [] ERROR - HL7TransportSender Error while sending an HL7 message
org.apache.axis2.AxisFault: Error while obtaining HL7 connection to: hl7://192.9.200.95:2001
        at org.apache.axis2.transport.base.AbstractTransportSender.handleException(AbstractTransportSender.java:226)
        at org.wso2.carbon.business.messaging.hl7.transport.HL7TransportSender.getConnection(HL7TransportSender.java:96)
        at org.wso2.carbon.business.messaging.hl7.transport.HL7TransportSender.sendUsingEPR(HL7TransportSender.java:153)
        at org.wso2.carbon.business.messaging.hl7.transport.HL7TransportSender.sendMessage(HL7TransportSender.java:67)
        at org.apache.axis2.transport.base.AbstractTransportSender.invoke(AbstractTransportSender.java:112)
        at org.apache.axis2.engine.AxisEngine.send(AxisEngine.java:442)
        at org.apache.axis2.description.OutInAxisOperationClient.send(OutInAxisOperation.java:430)
        at org.apache.axis2.description.OutInAxisOperationClient.executeImpl(OutInAxisOperation.java:225)
        at org.apache.axis2.client.OperationClient.execute(OperationClient.java:149)
        at org.apache.synapse.message.senders.blocking.BlockingMsgSender.sendReceive(BlockingMsgSender.java:300)
        at org.apache.synapse.message.senders.blocking.BlockingMsgSender.send(BlockingMsgSender.java:211)
        at org.apache.synapse.message.processor.impl.forwarder.ForwardingService.dispatch(ForwardingService.java:468)
        at org.apache.synapse.message.processor.impl.forwarder.ForwardingService.execute(ForwardingService.java:204)
        at org.wso2.carbon.mediation.ntask.NTaskAdapter.execute(NTaskAdapter.java:98)
        at org.wso2.carbon.ntask.core.impl.TaskQuartzJobAdapter.execute(TaskQuartzJobAdapter.java:67)
        at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: ca.uhn.hl7v2.HL7Exception: Cannot open connection to 192.9.200.95:2001/0
        at ca.uhn.hl7v2.app.ConnectionHub.attach(ConnectionHub.java:122)
        at ca.uhn.hl7v2.app.ConnectionHub.attach(ConnectionHub.java:172)
        at ca.uhn.hl7v2.app.ConnectionHub.attach(ConnectionHub.java:164)
        at ca.uhn.hl7v2.app.ConnectionHub.attach(ConnectionHub.java:216)
        at ca.uhn.hl7v2.app.ConnectionHub.attach(ConnectionHub.java:208)
        at org.wso2.carbon.business.messaging.hl7.transport.HL7TransportSender.getConnection(HL7TransportSender.java:91)
        ... 19 more
Caused by: java.net.ConnectException: Connection refused: connect
        at java.net.DualStackPlainSocketImpl.connect0(Native Method)
        at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:79)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at java.net.Socket.connect(Socket.java:538)
        at ca.uhn.hl7v2.app.ConnectionFactory.createSocket(ConnectionFactory.java:67)
        at ca.uhn.hl7v2.app.ConnectionFactory.open(ConnectionFactory.java:43)
        at ca.uhn.hl7v2.app.ConnectionHub$1.open(ConnectionHub.java:94)
        at ca.uhn.hl7v2.app.ConnectionHub$1.open(ConnectionHub.java:85)
        at ca.uhn.hl7v2.app.ConnectionHub$CountingMap.put(ConnectionHub.java:386)
        at ca.uhn.hl7v2.app.ConnectionHub.attach(ConnectionHub.java:117)
        ... 24 more
[2017-03-27 16:11:38,561] []  INFO - LogMediator MSG = in **replyLogSeq**, MSA1 = , MSH10 = IT0072PK4N6H`

**Comment by marcses** [comment] 2017-03-28 07:28
I have found an mistake on my configuration. The cause is the property 
`<property name="FORCE_SC_ACCEPTED" scope="axis2" type="STRING" value="true"/>` instead of
`<property name="FORCE_SC_ACCEPTED" scope="axis2" type="STRING" value="false"/>`
Setting to false FORCE_SC_ACCEPTED the faultSequence trigger good.
I'm sorry,
thanks

**Comment by marcses** [comment] 2017-03-28 08:30
After server restart, also with  FORCE_SC_ACCEPTED = false, the problem recurs.
I have uploaded my car application zipped. I have renamed .zip to .gif
I have attached the log

![compositeapp_1 0 26](https://cloud.githubusercontent.com/assets/26251486/24395597/790025b0-13a0-11e7-8a68-d39f90fbf893.gif)
[log.txt](https://github.com/wso2/product-ei/files/874935/log.txt)

**Comment by vinok88** [comment] 2017-03-28 08:47
We have identified the root cause for this issue. Will keep you posted with the fix.
Thanks for reporting this.

**Comment by marcses** [comment] 2017-03-28 10:02
Thanks

**Comment by vinok88** [comment] 2017-04-03 04:58
Closing the issue since this is fixed by https://github.com/wso2/wso2-synapse/pull/724.

**Closed by vinok88** 2017-04-03 04:58 UTC
Labels: bug, critical
